language: julia
julia:
  - release
notifications:
  email: true
before_script:
  - julia -e 'Pkg.add("Distributions")'
script:
  - julia -e 'include(string(pwd(),"/Hidden_Markov_Models/HMM_tests.jl"))'
