language: julia
julia:
  - release
notifications:
  email: false
before_script:
  - julia -e 'Pkg.add("Distributions")'
  - julia -e 'Pkg.add("NLsolve")'
script:
  - julia -e 'include("test_all.jl")'
