language: julia
julia:
  - release
notifications:
  email: false
script:
  - julia -e 'include(string(pwd(),"/Hidden_Markov_Model/HMM_functions.jl")); include(string(pwd(),"/Hidden_Markov_Model/HMM_tests.jl"))'
